### ISSUE TITLE
Layout issue on Retina Display: navbar

### ISSUE THREAD

**Issue by defuz** [BonsaiDen/JavaScript-Garden#179]
It seems the issue #171 is not completely solved. There is screenshot from my retina display:
![2013-05-27 01 16 40](https://f.cloud.github.com/assets/276041/565943/fbb26310-c651-11e2-83fe-30d1579f3c52.png)

On my screen, this rule applies:
```
@media screen and (max-width: 600px),
screen and (-webkit-min-device-pixel-ratio: 2) {
    #nav_main > ul > li {
        width: 25%;
    }
}
```
Change the width to 50% solve the problem, but I'm not sure this approach is correct for other types of screens.

**Comment by peterjwest** [comment]
Just tested, looks great!

**Comment by defuz** [comment]
:+1:
