### ISSUE TITLE
The delete Operator behaviour in Firefox

### ISSUE THREAD

**Issue by mieszko4** [BonsaiDen/JavaScript-Garden#181]
In "Global code and Function code" it says in the example that in global scope the following will happen:
// global variable:
var a = 1; // DontDelete is set
delete a; // false

This is not true for Firefox v. 22; you CAN delete global variables using its engine.

**Comment by siddharthkp** [comment]
Can we add a ES5 tiny tip on the side that this examples doesn't work anymore?
