### ISSUE TITLE
опечатка

### ISSUE THREAD

**Issue by killv** [BonsaiDen/JavaScript-Garden#258]
"...Итерации по массивам и !!!свойства

Несмотря..."

**Comment by AltynDaur** [comment]
He tells about typo in russian version. In topic "Objects", in subsection "The for in Loop" you have hasOwnPropery, but expected hasOwnProperty

**Comment by timruffles** [comment]
Thanks, would welcome a pull request! :) Closing as we need a Russian speaker to deal with this.
