### ISSUE TITLE
"it does not support block scope" is kinda false.

### ISSUE THREAD

**Issue by chrisranderson** [BonsaiDen/JavaScript-Garden#270]
I noticed there are ES5 notes - it might be good to add an ES6 note letting folks know that block scope will be available using `let`.

**Comment by timruffles** [comment]
PRs welcome!

Adding ES6 into the docs will be quite a big undertaking - definitely
important tho.

**Comment by peterjwest** [comment]
I think it's important we don't confuse or overwhelm beginner users coming to the site, ES6 is still not relevant to most javascript users, perhaps this could be a separate section or page.

**Comment by timruffles** [comment]
True.

**Comment by timruffles** [comment]
Closed - will be covered when we talk about ES6.
