### ISSUE TITLE
Found a bug in garden.js

### ISSUE THREAD

**Issue by remz** [BonsaiDen/JavaScript-Garden#281]
Sorry I don't know how to do a pull-request, but I think I found a bug in garden.js...
In the `mainNav.slideUp` event handler: `this` has no `removeAttr` function.

On line 187:
was:  
```javascript 
    mainNav.slideUp(300, function() {this.removeAttr('style');});
```
fixed: 
```javascript 
    mainNav.slideUp(300, function() {$('#nav_main').removeAttr('style');});
```

**Comment by peterjwest** [comment]
Thanks, I'll look into it!

**Comment by fediev** [comment]
PR #267 fixed this bug. I think your version is not up to date. Please, check again. Thanks.

**Comment by peterjwest** [comment]
Yep, this bug is already fixed, thanks for your effort, though.
