### ISSUE TITLE
Object.prototype.toString() behaviour

### ISSUE THREAD

**Issue by artptr** [BonsaiDen/JavaScript-Garden#285]
According to "The Class of an Object" section, the method `Object.prototype.toString()`returns `[[Class]]` internal value. But according to the [section 15.2.4.2](http://www.ecma-international.org/ecma-262/5.1/#sec-15.2.4.2) of the ECMAScript 5.1 Specification, this method should return string values like `'[object Null]'`, `'[object Undefined]'`, `'[object String]'`, etc.

**Comment by timruffles** [comment]
You're right, the text isn't clear. Will update!

**Comment by timruffles** [comment]
deployed
