### ISSUE TITLE
Is the ',' in ‘console.log(i, '' + obj[i]);’ wrong?

### ISSUE THREAD

**Issue by ryangun** [BonsaiDen/JavaScript-Garden#298]
Is the ',' in ‘console.log(i, '' + obj[i]);’ wrong?It's rather '+'?
![qq 20150724152706](https://cloud.githubusercontent.com/assets/3684807/8869633/a7b93fc4-3218-11e5-8131-3430cc8d927c.png)

**Comment by peterjwest** [comment]
You can give multiple arguments to console.log :)
