### ISSUE TITLE
Improper translation of a sentence

### ISSUE THREAD

**Issue by xis19** [BonsaiDen/JavaScript-Garden#302]
Original sentence:

It is for example fairly trivial to build a classic model on top of it, while the other way around is a far more difficult task.

The current translation is:

实现传统的类继承模型是很简单，但是实现 JavaScript 中的原型继承则要困难的多。

A more proper translation would be:

例如，（通过Prototype继承方式）实现传统继承模型是相对容易的，但是反过来（通过传统继承模型）实现Prototype继承则相当困难。

**Comment by timruffles** [comment]
Super - please could you open a pull-request with this change? Happy to merge.
