### ISSUE TITLE
es2015 (es6) version

### ISSUE THREAD

**Issue by arturparkhisenko** [BonsaiDen/JavaScript-Garden#307]
And pls, don't remove an old version, maybe we got a select input where we can switch them at anytime.

**Comment by timruffles** [comment]
Sure - welcome PRs on this :)

**Comment by adolfov** [comment]
why was this closed? can I still work on the pr?

**Comment by peterjwest** [comment]
Closed because of inactivity. Re can re-open and would welcome PRs
