### ISSUE TITLE
我觉得“字面值”翻译为“字面量“更合适些

### ISSUE THREAD

**Issue by suifengtec** [BonsaiDen/JavaScript-Garden#309]
http://bonsaiden.github.io/JavaScript-Garden/zh/

**Comment by suifengtec** [comment]
比如”数字的字面值“写成”数值的字面量“，会更顺些。

**Comment by suifengtec** [comment]
对象的字面语法：对象的字面量

**Comment by suifengtec** [comment]
另外呢，就是建议为各个小节加上id，以方便引用。

**Comment by AbrahamGreyson** [comment]
@suifengtec  问题不会自己消失， 你可以发起 pr。

**Comment by timruffles** [comment]
Sorry - please could you make a PR?
