### ISSUE TITLE
typos in Italian translation

### ISSUE THREAD

**Issue by roccomuso** [BonsaiDen/JavaScript-Garden#310]
There are some inaccuracies in the Italian translation:

    funzione anonima come funzione di callback ad un'altra, possibilmente asincrona, funzione.

Even this code is wrong, Test() should be replaced with Person():

    function Person() {
        this.someValue = 2;
        
        return {
        name: 'Charles'
        };
    }
    
    new Test();

or again:

    tutti i metodi da un altro oggetto oppure mettere quell'oggetto nel proptotipo del nuovo oggetto

    // la dichiarazione function viene spostate qui

**Comment by timruffles** [comment]
Please reopen as a pull request. You can edit [directly in github](https://github.com/BonsaiDen/JavaScript-Garden/edit/master/doc/it/function/general.md) if you like.
