### ISSUE TITLE
No quotes in object keys

### ISSUE THREAD

**Issue by NikitaLiashenko** [BonsaiDen/JavaScript-Garden#315]
You wrote that if you write object in such way:
var obj = {
    'option': 'This is template string',
    new_option : 'This is another template'
}
there will be Syntax error on new_option line, cause you should put it incide quotes. In modern JavaScript, you can write without quotes and it won't be any error.
Saw this in Russian localisation.

**Comment by timruffles** [comment]
Thanks! Please include this in a PR and we'll merge.

**Comment by lewisje** [comment]
The relevant section must have changed, but `new_option` is a valid variable identifier, so it can be an unquoted property key even in older engines.
