### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by splatonov92** [BonsaiDen/JavaScript-Garden#319]
Замыкания и ссылки
Одним из самых мощных инструментов** язка **JavaScript считают возможность

**Comment by splatonov92** [comment]
также в разделе "Пространства имён"
"поэтому, чтобы вы сделать их исполняемыми, следует спровоцировать их разбор."

**Comment by svarnoi420** [comment]
Не легче ли сделать pull request с исправлением?

**P.S.: ** Думаю стоит писать на английском языке. Так точно ответят.

**Comment by timruffles** [comment]
Thanks, please make a PR!
