### ISSUE TITLE
ES translation issue in "Notation of Keys" section.

### ISSUE THREAD

**Issue by jurrabi** [BonsaiDen/JavaScript-Garden#361]
Hi there (thanks and great work),

I don't know if this is the best way to report a translation issue. Just let me know if it isn't and, if you can, redirect me to the proper channel.

To the point. There is a translation error (into Spanish) in the "Notation of Keys" section of the "JavaScript Garden", just before "The prototype" section.

The original English text reads:
"This error arises from the fact that delete is a keyword;"
And the translation reads:
"Este error se debe al eliminar una keyword;" that  means "The error is due to deleting a keyword". Also it translates a language keyword, and that I think is wrong.

A better translation might be (just a suggestion):
"Este error se produce porque delete es una palabra clave;"

Thanks for your time and al the great work put into the garden... It's green and beautiful.

**Comment by peterjwest** [comment]
Thanks! If you could make a pull request we'd be happy to merge it. It would make it easier for you to fix more mistakes too ;)

**Comment by jurrabi** [comment]
I could do that but, Isn't there a responsible for translation? I wouldn't like to step over anybodies toes...

**Comment by Cryptoxygen** [comment]
> Thanks! If you could make a pull request we'd be happy to merge it. It would make it easier for you to fix more mistakes too ;)

Yeahh ! I agree.

**Comment by peterjwest** [comment]
Closing as this has been resolved.
