### ISSUE TITLE
使用typeof检测一个未定义的变量时，是不会报错的。

### ISSUE THREAD

**Issue by CodingYiyi** [BonsaiDen/JavaScript-Garden#376]
原文：
测试为定义变量
typeof foo !== 'undefined'
上面代码会检测 foo 是否已经定义；如果没有定义而直接使用会导致 ReferenceError 的异常。 这是 typeof 唯一有用的地方。

实际情况：
使用typeof检测变量时，无论是未声明，还是只声明未赋值，返回的都是“undefined”

**Comment by peterjwest** [comment]
Sorry, I don't understand, none of the maintainers speak Mandarin.

**Comment by jiangwenyang** [comment]
@CodingYiyi 这段话的含义是说如果直接使用 `foo!==undefined` 将会报错，而使用`typeof foo !== 'undefined'`不会报错，因此这是typeof唯一有用的地方，是你自己没有认真阅读哦。

**Comment by CodingYiyi** [comment]
@jiangwenyang you are right,I'm wrong. sori
