### ISSUE TITLE
The github page is not work

### ISSUE THREAD

**Issue by Michael18811380328** [BonsaiDen/JavaScript-Garden#381]
This website can't work well (http://bonsaiden.github.io/JavaScript-Garden).

**Comment by peterjwest** [comment]
It works for me, can you send a screenshot? What country are you in?

**Comment by Michael18811380328** [comment]
I entered this website 17 days ago and found page was empty. Maybe the github page is wrong (server error 500). The site can now be successfully loaded now. Thank you.
