### ISSUE TITLE
primitives will simply get ignored when assigned as a prototype. is this right?

### ISSUE THREAD

**Issue by idkiller** [BonsaiDen/JavaScript-Garden#89]
in chapter "The prototype"

<pre>
The Prototype Property

While the prototype property is used by the language to build the prototype chains, it is still possible to assign any given value to it. Although primitives will simply get ignored when assigned as a prototype.
</pre>

is this really right?

when I test at firefox and chrome, assigned primitives really change prototype.

```
function foo() { this.x = 10; }

function bar() {}

bar.prototype = new foo();

bar.prototype = 1; // it was not ignored. prototype has changed really.
```

**Comment by evverx** [comment]
```
However, primitives will simply get ignored when assigned as a prototype.
```
```javascript
function Foo() {}
Foo.prototype = 1; // no effect
```
Really?:)

```javascript
function Foo() {}
(new Foo).constructor === Foo;
```

```javascript
function Foo() {}
Foo.prototype = 1;
(new Foo).constructor === Object;
```
but who cares? :)

The default `Foo.prototype` object by default gets a public, non-enumerable property called `.constructor`, and this property is a reference back to the function (`Foo` in this case) that the object is associated with. See [Creating Function Objects](http://es5.github.io/#x13.2)

`Foo.prototype = 1` sets `prototype` property to non-object value.
Quote from ES5 [Construct](http://es5.github.io/#x13.2.2):
```
If Type(proto) is not Object, set the [[Prototype]] internal property of obj to the standard built-in Object prototype object as described in 15.2.4.
```

**Comment by timruffles** [comment]
PRs always welcome :)

**Comment by evverx** [comment]
Yes, I know :) I'm reading and collecting inaccuracies now. Maybe I'll be back with PRs :)
